# Generated by Django 2.0 on 2018-11-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduit', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=42)),
                ('description', models.TextField(null=True)),
                ('collection', models.CharField(max_length=42)),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['marque'],
            },
        ),
    ]
