# Generated by Django 2.0 on 2018-11-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
