# Generated by Django 2.0 on 2018-11-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20181130_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='URL',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to="os.path.join(BASE_DIR, 'media/')"),
        ),
    ]
