# Generated by Django 2.0 on 2018-12-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20181204_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='produits',
            field=models.ManyToManyField(related_name='marques', to='ecommerce.Article'),
        ),
    ]
