# Generated by Django 2.0 on 2018-12-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_marque_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='marque',
        ),
    ]
