# Generated by Django 2.0 on 2018-12-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_remove_article_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='marque',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Marque'),
        ),
    ]
