# Generated by Django 2.0 on 2018-12-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_article_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/media/img/GarmsSmallLogo.jpg', upload_to='photos/'),
        ),
    ]
