# Generated by Django 2.0 on 2018-12-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20181210_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCollection', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='photos/')),
            ],
            options={
                'verbose_name': 'collection',
                'ordering': ['nomCollection'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='collection',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='../../../../../static/img/GarmsSmallLogo.jpg', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='collection',
            name='produits',
            field=models.ManyToManyField(related_name='collections', to='ecommerce.Article'),
        ),
    ]
