# Generated by Django 2.0 on 2018-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20181211_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='../../../../../static/img/GarmsSmallLogo.jpg', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='marque',
            name='image',
            field=models.ImageField(default='../../../../../static/img/GarmsSmallLogo.jpg', upload_to='photos/'),
        ),
    ]
