# Generated by Django 2.0 on 2018-12-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20181206_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='marque',
        ),
    ]
