# Generated by Django 2.0 on 2018-12-20 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20181211_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='promoSlideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('content', models.CharField(max_length=100)),
                ('image', models.ImageField(default='../../../../../static/img/GarmsSmallLogo.jpg', upload_to='photos/')),
                ('marque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Marque')),
            ],
        ),
    ]
