# Generated by Django 2.0 on 2018-12-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_article_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='marque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Marque'),
        ),
    ]
