# Generated by Django 2.0 on 2019-01-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_promoslideshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPage', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(default='../../../../../static/img/GarmsSmallLogo.jpg', upload_to='photos/')),
            ],
            options={
                'verbose_name': 'page',
                'ordering': ['nomPage'],
            },
        ),
    ]
