# Generated by Django 2.0 on 2019-01-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoslideshow',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
